-- MADE --HW3
made-mlops-2022/Naumenko_Konstantin pull request #3
Opened 2022-12-08 18:50 UTC by Naumenko-KM

Здравствуйте, сделал базовую часть дз. 
1. Dag генерирует данные ирисов (случайная выборка из датасета) и записывает. (5 баллов)
2. Dag обучает модель в 4 стадии использую данные за текущий день. (10 баллов)
3. Dag делает предсказания каждый день с выбранной моделью из variables и записывает. (5 баллов)
4. Все даги реализованы только с помощью докера, некоторые таски используют один контейнер. (5 + 10 баллов)
5. Самооценка есть. (1 балл)
Доп. часть не делал, т.к. неделю проболел ОРВИ.
Итог: 36 баллов, после дедлайна 36 * 0,6 =  21,6 балла

2022-12-24 22:35 UTC, SVizor42 commented on airflow_ml_dags/docker-compose.yml
> +  - AIRFLOW__CORE__LOAD_EXAMPLES=True
Можно отключить примеры, чтобы не мешали

2022-12-24 22:40 UTC, SVizor42 requested changes
Комментарии:
1. Нужно добавить метки `MADE`\`TECHNOPARK` и `hw3`.
2. Необходимо удалить посторонние папки (`__pycahe__`).
3. Cейча PR настроен на мердж из ветки `dev` в  `homework3`.  Так и задумывалось?

2022-12-25 13:32 UTC, Naumenko-KM commented
Метки добавил, pycache удалил.
Да, разработка велась в dev, далее сделал мердж в homework3

2022-12-25 13:33 UTC, Naumenko-KM commented
Метки добавил, pycache удалил.
Да, разработка велась в dev, далее сделал мердж в homework3

2022-12-25 16:20 UTC, SVizor42 approved these changes
Хорошо.

По поводу п. 4 - там баллы не суммируются, а возможен только один из вариантов (1, 5 или 10 баллов).

**Сумма: 31 * 0.6 = 18.6 балла**

Ветку можно сливать, если нет возражений.

2022-12-25 16:22 UTC, merged